### ISSUE TITLE
Migrate to Github

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-react-ui#1]
- check and resolve pending PR's
- import from internal bitbucket to github
- add deprecation message to bitbucket
- migrate unresolved PR's
- prune unnecessary branches
- fix README, package*, NOTICE/LICENSE
- ~~publish under `@marklogic-community`~~

**Comment by grtjn** [comment]
Created #2 to review branches, and skipped deprecation message for now, otherwise all done.

**Comment by withjam** [comment]
We can call this done now, correct?

**Comment by mariannemyers** [comment]
Yes, we can.

**Comment by mariannemyers** [comment]
This is complete.  Closing issue.
