### ISSUE TITLE
"REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: No configured options: all" on search

### ISSUE THREAD

**Issue by Brendan-NTT** [marklogic-community/grove-react-ui#14]
After installing the latest version of Grove and configuring to communicate with MarkLogic using SSL using the following .env entry : GROVE_HTTPS_ENABLED_IN_BACKEND=true 

I get the following error when searching the database :  "REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: No configured options: all"

**Comment by grtjn** [comment]
The Grove template comes with a search options file called all.xml. Sounds like you didn't deploy it. Maybe you replaced the Grove backend with a DHF/DHS of your own? In that case, pick a search option that is available instead, like final-entity-options, or include all.xml in the DHF deployment. You could also copy a generated options like final-entity-options, and save it as all.xml. If you decide not to use all.xml, you have to specify a different options file in the search route at middle-tier/routes/api/index.js

**Comment by Brendan-NTT** [comment]
Thanks for the response - it is hugely appreciated.  I just followed the instructions here : https://marklogic-community.github.io/grove/guides/getting-started/ 

As I have already run mlDeploy for the data hub framework deploy I didn't want to run mlDeploy again. This is my first time doing the installation of the MarkLogic/Data Hub Framework/Grove ecosystem so I am trying to follow the MarkLogic instructions and piece the different bits and pieces together but I am finding it very unintuitive.

I can see that there is a all.xml file in the marklogic/src/main/ui-modules folder. Where should I copy this to in order for the middle tier to be able to access it?

**Comment by grtjn** [comment]
The DHF mlDeploy is fine, and you don't have to run the Grove mlDeploy. Instead, we have specific instruction on how to attach Grove to DHF. The full-blown way is described here: https://marklogic-community.github.io/grove/guides/data-hub-framework/ (most people follow the top part). There are shorter ways, but the longer approach is only a few steps extra.

**Comment by Brendan-NTT** [comment]
Thanks you for going the extra mile and providing me with the additional information. This issue has been identified as PEBKAC and closed.
